### ISSUE TITLE
Sonoff app unable to discover new Sonoff S20 (Tasmota)

### ISSUE THREAD

**Issue by rhannink** [robertklep/name.klep.sonoff#20]
Hello,

I have a Sonoff S20 with Tasmota 6.2.1 and 6.3.0 firmware. When I reboot them, I see all information in my MQTT server:

INFO1
INFO2
INFO3
STATUS
etc.

But When I try to add a device in Homey and reboot the Sonoff, it does not find any new device.

any idea ??

Gr. Remco

**Comment by robertklep** [comment]
Can you post the specific contents of those MQTT messages?

**Comment by rhannink** [comment]
`14:36:19 MQT: Connected
14:36:19 MQT: tele/sonoff-kerstkrans/LWT = Online (retained)
14:36:19 MQT: cmnd/sonoff-kerstkrans/POWER = 
14:36:19 MQT: tele/sonoff-kerstkrans/INFO1 = {"Module":"Sonoff S2X","Version":"6.3.0","FallbackTopic":"DVES_1BD066","GroupTopic":"sonoffs"}
14:36:19 MQT: tele/sonoff-kerstkrans/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-kerstkrans-4198","IPAddress":"192.168.1.108"}
14:36:19 MQT: tele/sonoff-kerstkrans/INFO3 = {"RestartReason":"Power on"}
14:36:19 MQT: stat/sonoff-kerstkrans/RESULT = {"POWER":"ON"}
14:36:19 MQT: stat/sonoff-kerstkrans/POWER = ON
14:36:19 MQT: stat/sonoff-kerstkrans/STATUS5 = {"StatusNET":{"Hostname":"sonoff-kerstkrans-4198","IPAddress":"192.168.1.108","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.22","Mac":"5C:CF:7F:1B:D0:66","Webserver":2,"WifiConfig":2}}
14:36:28 MQT: tele/sonoff-kerstkrans/STATE = {"Time":"2018-12-08T14:36:28","Uptime":"0T00:00:17","Vcc":3.161,"POWER":"ON","Wifi":{"AP":1,"SSId":"hannink.org","BSSId":"02:9F:C2:F7:BF:28","Channel":11,"RSSI":86}}
14:41:28 MQT: tele/sonoff-kerstkrans/STATE = {"Time":"2018-12-08T14:41:28","Uptime":"0T00:05:17","Vcc":3.164,"POWER":"ON","Wifi":{"AP":1,"SSId":"hannink.org","BSSId":"02:9F:C2:F7:BF:28","Channel":11,"RSSI":84}}`

**Comment by robertklep** [comment]
Try configuring it as a "Sonoff Basic" for the time being. The problem is that the identifier for the S20 changed from "S20" to "S2X", and the current version of the app doesn't yet know that identifier.

It's already fixed in my local version, but it's taking more time than anticipated to publish that as a new app version (because besides this problem, there's a lot of under the hood functionality added).

The Basic has the same functionality as the S20, that's why that driver should work too (although it won't have the pretty S20 icon 😅).

**Comment by rhannink** [comment]
I have added the device before to Homey, but I deleted it, changed the name and the MQTT Topic.

**Comment by rhannink** [comment]
Still no luck Robert, I tried to add a generic Sonoff (Tasmota) but seem problem.

**Comment by robertklep** [comment]
The generic Sonoff (Tasmota) driver might also not work.

Configure the module as "Basic" (in the Tasmota configuration):
![image](https://user-images.githubusercontent.com/1190916/49686738-1cb19180-faf9-11e8-9f9b-c73c788edb9a.png)

And add it as a "Basic (Tasmota)" device to Homey:
![image](https://user-images.githubusercontent.com/1190916/49686728-fdb2ff80-faf8-11e8-9d25-294f72b12166.png)

**Comment by rhannink** [comment]
Robert,

I tried the Basic Sonoff (Tasmota), that did not work. 
I chose the Generic (Tasmota) and that worked. I could even select the correct model (S20).
Everything is fine now, thanks for the support.

**Comment by robertklep** [comment]
Strange! But good to know it worked ;)

**Comment by rhannink** [comment]
Robert, I just saw now you asked me to change to generic Sonoff in the Tasmota software. I changed in Homey to Generic (Tasmota) and that also worked, including stetting the correct Sonoff type and icon .......cheers.
